import { useSession, signIn, signOut } from "next-auth/react";
import {
  Button,
  Container,
  Heading,
  Text,
  Flex,
  Box,
  Center,
  VStack,
} from "@chakra-ui/react";
import Head from "next/head";
import MenuBar from "@/components/menuBar";

export default function Home() {
  const { data: session } = useSession();

  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      {session ? (
        <Flex gap="300px" justify="space-between" align="center">
          <MenuBar />
          <VStack spacing={2}>
            <Text>Signed in as {session.user.email}</Text>
            <Button onClick={() => signOut()} size="sm">Sign out</Button>
          </VStack>
        </Flex>
      ) : (
        <Center p={8}>
          <Box mt={4}>
            <Text w="100px" mb="20px">
              Not signed in
            </Text>
            <Button onClick={() => signIn()} bg="purple.500" w="100px">
              Sign in
            </Button>
          </Box>
        </Center>
      )}

      <Container p="20px" centerContent="true">
        <Heading size="3xl">Homepage</Heading>
        <Text mt="3.5" bg="purple.500" color="white">
          Welcome to favorite cities website!
        </Text>
      </Container>
    </>
  );
}